<?php
/**
 * Precision Manufacturing B2B theme demo.
 *
 * Loaded by ThemeDemoService (panel "import demo") and by the installer when the
 * customer opts into this theme. Truncates CMS content, (re)publishes the bundled
 * demo images to public/static/themes/precision/images, then seeds the fictional
 * "Apex Precision / 傲锋精密" B2B site.
 *
 * @link       https://www.innocms.com
 * @author     InnoCMS <team@innoshop.com>
 * @license    https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */

use Illuminate\Support\Facades\DB;
use InnoCMS\Common\Models\Article;
use InnoCMS\Common\Models\ArticleTag;
use InnoCMS\Common\Models\Catalog;
use InnoCMS\Common\Models\Page;
use InnoCMS\Common\Models\Setting;
use InnoCMS\Common\Models\Tag;

return function (string $themeDir): void {
    $themeCode = basename($themeDir);
    $img       = static fn (string $rel): string => 'static/themes/'.$themeCode.'/images/'.$rel;

    precision_truncate();
    precision_seed_settings();
    precision_seed_catalogs();
    precision_seed_tags();
    precision_seed_articles($img);
    precision_seed_pages($img);
};

function precision_truncate(): void
{
    $driver = DB::getDriverName();
    $off    = $driver === 'sqlite' ? 'PRAGMA foreign_keys = OFF' : 'SET FOREIGN_KEY_CHECKS=0';
    $on     = $driver === 'sqlite' ? 'PRAGMA foreign_keys = ON' : 'SET FOREIGN_KEY_CHECKS=1';
    DB::statement($off);
    foreach ([ArticleTag::class, Article\Translation::class, Article::class, Catalog\Translation::class, Catalog::class, Page\Translation::class, Page::class, Tag\Translation::class, Tag::class] as $m) {
        $m::query()->truncate();
    }
    DB::statement($on);
}

function precision_seed_settings(): void
{
    $values = [
        'theme'            => 'precision',
        'meta_title'       => '傲锋精密 Apex Precision - CNC加工|钣金|压铸一站式精密零部件制造商',
        'meta_keywords'    => 'CNC加工,精密零件,五轴加工,钣金加工,压铸,阳极氧化,OEM/ODM,傲锋精密,Apex Precision',
        'meta_description' => '傲锋精密（Apex Precision）成立于 2008 年，提供 CNC 加工、钣金、压铸与表面处理一站式精密零部件制造服务，通过 ISO 9001 / IATF 16949 / ISO 13485 认证，产品远销 30 多个国家和地区。',
        'contact_phone'    => '+86-769-8123-4567',
        'contact_email'    => 'sales@apexprecision.cn',
        'contact_address'  => 'Dongguan, China',
        'contact_hours'    => 'Mon-Sat 8:30-18:00 (GMT+8)',
    ];
    foreach ($values as $name => $value) {
        Setting::query()->updateOrInsert(['space' => 'system', 'name' => $name], ['value' => $value, 'json' => 0]);
    }
}

function precision_seed_catalogs(): void
{
    $rows = [
        [1, 0, 'products', 1, '产品中心', 'Products', '从 CNC 加工、钣金、压铸到表面处理的一站式精密零部件制造服务。', 'One-stop precision parts manufacturing: CNC machining, sheet metal, die casting and surface finishing.'],
        [2, 1, 'cnc-machining', 1, 'CNC加工', 'CNC Machining', '3轴/5轴 CNC 铣削与车削，公差可达 ±0.005mm，支持单件打样到批量生产。', '3-axis and 5-axis CNC milling and turning with tolerances down to ±0.005mm, from single prototypes to volume production.'],
        [3, 1, 'sheet-metal', 2, '钣金加工', 'Sheet Metal', '激光切割、折弯、焊接与铆接，定制机箱机柜与结构件。', 'Laser cutting, bending, welding and riveting for custom enclosures and structural parts.'],
        [4, 1, 'die-casting', 3, '压铸成型', 'Die Casting', '80–800T 压铸机，铝合金与锌合金压铸件，适合大批量轻量化结构件。', '80–800T die casting machines for aluminum and zinc alloy parts, ideal for high-volume lightweight structures.'],
        [5, 1, 'surface-finishing', 4, '表面处理', 'Surface Finishing', '阳极氧化、喷粉、电镀、抛光与钝化，提升零件性能与外观。', 'Anodizing, powder coating, electroplating, polishing and passivation to enhance performance and appearance.'],
        [6, 0, 'industries', 2, '行业应用', 'Industries', '为汽车、医疗、航空航天与消费电子等行业提供合规、可靠的精密零部件。', 'Compliant, reliable precision components for automotive, medical, aerospace and consumer electronics.'],
        [7, 6, 'automotive', 1, '汽车制造', 'Automotive', 'IATF 16949 体系下的汽车精密零部件与新能源三电系统结构件。', 'IATF 16949 certified automotive components and structural parts for new-energy EV systems.'],
        [8, 6, 'medical', 2, '医疗器械', 'Medical', 'ISO 13485 受控流程，医疗仪器外壳、手术器械零件与植入类试制件。', 'ISO 13485 controlled processes for medical housings, surgical instrument parts and implant prototypes.'],
        [9, 6, 'aerospace', 3, '航空航天', 'Aerospace', '钛合金、高温合金等难加工材料的航空航天零部件加工。', 'Aerospace machining of difficult materials including titanium and superalloys.'],
        [10, 6, 'electronics', 4, '消费电子', 'Electronics', '精密电子外壳、散热器、连接器与屏蔽罩，兼顾外观与精度。', 'Precision electronic housings, heat sinks, connectors and shielding with cosmetic-grade finishes.'],
        [11, 0, 'news', 3, '新闻资讯', 'News', '公司新闻与行业动态，了解傲锋精密的最新进展与制造技术趋势。', 'Company announcements and industry insights from Apex Precision.'],
        [12, 11, 'company-news', 1, '公司新闻', 'Company News', '傲锋精密的企业动态、认证更新与产能扩张进展。', 'Corporate updates, certifications and capacity expansion at Apex Precision.'],
        [13, 11, 'industry-news', 2, '行业动态', 'Industry News', '精密加工行业的技术趋势、供应链与市场观察。', 'Technology trends, supply chain and market observations in precision manufacturing.'],
    ];
    foreach ($rows as [$id, $parent, $slug, $pos, $zh, $en, $zhS, $enS]) {
        $catalog = Catalog::query()->create(['id' => $id, 'parent_id' => $parent, 'slug' => $slug, 'position' => $pos, 'active' => 1]);
        $catalog->translations()->createMany([
            ['locale' => 'zh-cn', 'title' => $zh, 'summary' => $zhS, 'meta_title' => $zh.'｜傲锋精密', 'meta_description' => $zhS, 'meta_keywords' => $zh.',傲锋精密,Apex Precision'],
            ['locale' => 'en', 'title' => $en, 'summary' => $enS, 'meta_title' => $en.' | Apex Precision', 'meta_description' => $enS, 'meta_keywords' => $en.', Apex Precision, precision manufacturing'],
        ]);
    }
}

function precision_seed_tags(): void
{
    $tags = [
        [1, 'cnc-machining', 'CNC加工', 'CNC Machining'],
        [2, 'precision-parts', '精密零件', 'Precision Parts'],
        [3, 'oem-odm', 'OEM/ODM', 'OEM/ODM'],
        [4, 'iso-9001', 'ISO 9001', 'ISO 9001'],
        [5, 'aluminum', '铝合金', 'Aluminum'],
        [6, 'stainless-steel', '不锈钢', 'Stainless Steel'],
        [7, 'five-axis', '五轴加工', '5-Axis'],
        [8, 'rapid-prototyping', '快速打样', 'Rapid Prototyping'],
    ];
    foreach ($tags as [$id, $slug, $zh, $en]) {
        Tag::query()->create(['id' => $id, 'slug' => $slug, 'position' => $id, 'active' => 1]);
        Tag\Translation::query()->create(['tag_id' => $id, 'locale' => 'zh-cn', 'name' => $zh]);
        Tag\Translation::query()->create(['tag_id' => $id, 'locale' => 'en', 'name' => $en]);
    }
}

/**
 * @return array<int, array{0:int,1:int,2:string,3:string,4:int,5:array<int,int>,6:array,7:array}>
 */
function precision_article_defs(): array
{
    return [
        [1, 1, 'custom-cnc-machining-parts', 'products/cnc-parts.jpg', 568, [1, 2, 3, 8],
            ['t' => '定制 CNC 加工件', 's' => '来图来样定制 CNC 加工件，公差可达 ±0.005mm，支持单件打样与批量生产，24 小时内快速报价。', 'c' => '<p>傲锋精密提供一站式定制 CNC 加工服务，根据您的 2D/3D 图纸加工铝合金、不锈钢、铜、钛合金及工程塑料零件，覆盖原型验证到量产交付的全流程。</p><h3>加工能力</h3><ul><li>55+ 台 CNC 加工中心，其中 12 台五轴联动设备</li><li>最大加工行程 1500 × 800 × 600 mm</li><li>公差可达 ±0.005mm，表面粗糙度 Ra 0.2</li><li>单件起订，打样周期 7–15 天</li></ul><h3>常用材料</h3><ul><li>铝合金：6061、6063、7075、5083</li><li>不锈钢：303、304、316L、17-4PH</li><li>铜合金：H62、C3604、铍铜</li><li>工程塑料：POM、PEEK、尼龙、PC</li></ul><h3>规格参数</h3><table class="table table-bordered"><tbody><tr><th>设备类型</th><td>3轴 / 4轴 / 5轴 CNC 铣削、车削、车铣复合</td></tr><tr><th>尺寸范围</th><td>1500 × 800 × 600 mm</td></tr><tr><th>公差</th><td>±0.005mm（依图纸与材料而定）</td></tr><tr><th>文件格式</th><td>STEP、IGS、X_T、PDF</td></tr><tr><th>批量范围</th><td>1 件 – 100,000 件</td></tr><tr><th>交期</th><td>打样 7–15 天，量产 25–35 天</td></tr></tbody></table><p>欢迎发送图纸至 <a href="mailto:sales@apexprecision.cn">sales@apexprecision.cn</a> 获取免费报价，我们将在 24 小时内回复。</p>'],
            ['t' => 'Custom CNC Machining Parts', 's' => 'Made-to-drawing CNC machined parts with tolerances down to ±0.005mm. Prototype to mass production, quoted within 24 hours.', 'c' => '<p>Apex Precision delivers one-stop custom CNC machining services, producing aluminum, stainless steel, brass, titanium and engineering plastic parts from your 2D/3D drawings — from prototype validation through mass production.</p><h3>Capabilities</h3><ul><li>55+ CNC machining centers, including 12 five-axis machines</li><li>Maximum machining envelope 1500 × 800 × 600 mm</li><li>Tolerances down to ±0.005mm, surface finish Ra 0.2</li><li>No minimum order, prototypes in 7–15 days</li></ul><h3>Common Materials</h3><ul><li>Aluminum: 6061, 6063, 7075, 5083</li><li>Stainless steel: 303, 304, 316L, 17-4PH</li><li>Brass &amp; copper: H62, C3604, beryllium copper</li><li>Engineering plastics: POM, PEEK, Nylon, PC</li></ul><h3>Specifications</h3><table class="table table-bordered"><tbody><tr><th>Equipment</th><td>3/4/5-axis CNC milling, turning, mill-turn</td></tr><tr><th>Part size</th><td>Up to 1500 × 800 × 600 mm</td></tr><tr><th>Tolerance</th><td>±0.005mm (drawing &amp; material dependent)</td></tr><tr><th>File formats</th><td>STEP, IGS, X_T, PDF</td></tr><tr><th>Volume</th><td>1 – 100,000 pcs</td></tr><tr><th>Lead time</th><td>Prototype 7–15 days, production 25–35 days</td></tr></tbody></table><p>Send your drawings to <a href="mailto:sales@apexprecision.cn">sales@apexprecision.cn</a> for a free quotation — we respond within 24 hours.</p>']],
        [2, 1, 'precision-milling-parts', 'products/precision-milling.jpg', 431, [1, 2, 5],
            ['t' => '精密铣削零件', 's' => '高精度 CNC 铣削加工，适合复杂型腔、薄壁与异形结构件，批量一致性好，尺寸稳定可控。', 'c' => '<p>精密铣削是傲锋的核心工艺之一。我们的高转速加工中心配合在线测头补偿，可稳定加工复杂型腔、深腔、薄壁（最薄 0.3mm）及异形曲面结构件。</p><h3>工艺优势</h3><ul><li>主轴转速最高 20,000 rpm，镜面级精加工</li><li>在线测量补偿，批量尺寸 CPK ≥ 1.33</li><li>真空夹具与专用工装，解决薄壁件变形难题</li><li>恒温车间（20 ± 2℃）保障测量与加工一致性</li></ul><h3>典型应用</h3><ul><li>自动化设备结构件与安装板</li><li>光学仪器支架与镜座</li><li>通讯腔体与散热基座</li><li>无人机机架与云台结构件</li></ul>'],
            ['t' => 'Precision Milling Parts', 's' => 'High-accuracy CNC milling for complex cavities, thin walls and freeform structures with stable batch consistency.', 'c' => '<p>Precision milling is one of Apex\'s core processes. Our high-speed machining centers with on-machine probing reliably produce complex cavities, deep pockets, thin walls (down to 0.3mm) and freeform surfaces.</p><h3>Process Advantages</h3><ul><li>Spindle speeds up to 20,000 rpm for mirror-grade finishing</li><li>On-machine measurement compensation, batch CPK ≥ 1.33</li><li>Vacuum fixtures and dedicated tooling for thin-wall stability</li><li>Temperature-controlled shop (20 ± 2℃) for measurement consistency</li></ul><h3>Typical Applications</h3><ul><li>Automation frames and mounting plates</li><li>Optical instrument brackets and lens mounts</li><li>Telecom cavities and heat-sink bases</li><li>Drone frames and gimbal structures</li></ul>']],
        [3, 1, 'five-axis-machining-service', 'products/5-axis-machining.jpg', 389, [1, 7, 8],
            ['t' => '五轴加工服务', 's' => '12 台五轴联动加工中心，一次装夹完成多面体复杂零件，减少装夹误差，缩短交期。', 'c' => '<p>五轴联动加工可在一次装夹中完成多面、多角度特征，消除重复定位误差，是叶轮、模具、医疗器械与航空结构件的理想工艺。</p><h3>为什么选择五轴</h3><ul><li>一次装夹加工 5 个面，位置度精度提升 50% 以上</li><li>刀具姿态优化，深腔与倒扣特征无需放电加工</li><li>工序集中，交期平均缩短 30%</li><li>适合钛合金、高温合金等难加工材料</li></ul><h3>设备配置</h3><ul><li>12 台五轴加工中心（摇篮式 + 摆头式）</li><li>行程 800 × 630 × 500 mm，重复定位精度 0.003mm</li><li>配套 CAM 团队，支持复杂曲面编程与仿真验证</li></ul>'],
            ['t' => '5-Axis Machining Service', 's' => 'Twelve simultaneous 5-axis centers complete complex multi-face parts in one setup — less error, shorter lead time.', 'c' => '<p>Simultaneous 5-axis machining completes multi-face, multi-angle features in a single setup, eliminating re-positioning error. It is the ideal process for impellers, molds, medical devices and aerospace structures.</p><h3>Why 5-Axis</h3><ul><li>Five faces in one setup — positional accuracy improved by over 50%</li><li>Optimized tool orientation removes the need for EDM on undercuts</li><li>Consolidated operations cut lead times by 30% on average</li><li>Well suited to titanium, Inconel and other difficult materials</li></ul><h3>Equipment</h3><ul><li>12 five-axis centers (trunnion and swivel-head configurations)</li><li>Envelope 800 × 630 × 500 mm, repeatability 0.003mm</li><li>Dedicated CAM team for complex surfacing and simulation</li></ul>']],
        [4, 1, 'precision-turning-parts', 'products/turned-parts.jpg', 356, [1, 2, 6],
            ['t' => '精密车削零件', 's' => 'CNC 车削与车铣复合加工，直径 0.5–500mm，擅长轴类、套类与接头类回转体零件。', 'c' => '<p>傲锋拥有 30 台 CNC 数控车床及车铣复合中心，专业加工各类回转体零件：传动轴、销轴、衬套、接头、阀体等。</p><h3>加工范围</h3><ul><li>车削直径 0.5–500mm，长度 ≤ 1200mm</li><li>车铣复合一次成型，同轴度 ≤ 0.01mm</li><li>棒料机自动送料，适合中小批量连续生产</li><li>支持螺纹、滚花、切槽等特征加工</li></ul><h3>质量控制</h3><ul><li>首件三坐标全尺寸报告</li><li>批量抽检 + 关键尺寸 100% 检测</li><li>材质证明与热处理报告随货提供</li></ul>'],
            ['t' => 'Precision Turning Parts', 's' => 'CNC turning and mill-turn machining from Ø0.5 to 500mm for shafts, bushings, fittings and other rotary parts.', 'c' => '<p>Apex operates 30 CNC lathes and mill-turn centers specialized in rotary parts: drive shafts, pins, bushings, fittings, valve bodies and more.</p><h3>Machining Range</h3><ul><li>Turning diameter 0.5–500mm, length ≤ 1200mm</li><li>Mill-turn complete machining, concentricity ≤ 0.01mm</li><li>Bar feeders for continuous small-to-medium batch production</li><li>Threading, knurling and grooving capabilities</li></ul><h3>Quality Control</h3><ul><li>First-article full CMM dimensional report</li><li>Batch sampling plus 100% inspection of critical dimensions</li><li>Material certificates and heat-treatment reports included</li></ul>']],
        [5, 2, 'aluminum-cnc-parts', 'products/aluminum-cnc.jpg', 312, [1, 5, 2],
            ['t' => '铝合金 CNC 加工件', 's' => '6061/7075 铝合金精密加工，切削效率高、成本可控，配套阳极氧化等表面工艺。', 'c' => '<p>铝合金是 CNC 加工中应用最广的材料，兼具轻量化、导热好、易加工与成本友好的优势。傲锋常备 6061-T6、6063、7075、5083 等牌号铝材，来料与自采均可。</p><h3>工艺要点</h3><ul><li>专用铝用刀具与高速切削参数，镜面效果可达 Ra 0.4</li><li>应力释放处理，防止薄壁件加工变形</li><li>配套阳极氧化（本色/黑色/彩色）、喷砂、拉丝</li></ul><h3>典型产品</h3><ul><li>无人机结构件、散热器、光学镜筒</li><li>自动化夹具、半导体设备腔体</li><li>消费电子金属外壳与按键</li></ul>'],
            ['t' => 'Aluminum CNC Parts', 's' => 'Precision machining of 6061/7075 aluminum — high cutting efficiency, controlled cost, with in-house anodizing.', 'c' => '<p>Aluminum is the most widely machined material, combining light weight, thermal conductivity, machinability and cost efficiency. Apex stocks 6061-T6, 6063, 7075 and 5083 grades; customer-supplied material is welcome.</p><h3>Process Highlights</h3><ul><li>Aluminum-specific tooling and HSM parameters, finishes to Ra 0.4</li><li>Stress-relief treatment prevents thin-wall distortion</li><li>In-house anodizing (clear/black/color), bead blasting, brushing</li></ul><h3>Typical Products</h3><ul><li>Drone frames, heat sinks, optical lens barrels</li><li>Automation fixtures, semiconductor chambers</li><li>Consumer electronics housings and buttons</li></ul>']],
        [6, 2, 'brass-cnc-parts', 'products/brass-cnc.jpg', 245, [1, 2],
            ['t' => '黄铜精密加工件', 's' => 'H59/H62/C3604 黄铜件加工，导电导热性能优异，适用于接头、阀门与电气端子。', 'c' => '<p>黄铜切削性能优异、表面光洁度高，并具备良好的导电导热与耐腐蚀性能，是流体接头、电气端子、阀门零件与装饰件的首选材料。</p><h3>服务范围</h3><ul><li>H59、H62、C3604 易切削黄铜，铍铜可定制</li><li>车削 + 铣削复合工艺，微小特征加工精度 ±0.01mm</li><li>配套镀镍、镀铬、钝化处理</li></ul><h3>应用场景</h3><ul><li>气动/液压接头、阀芯阀座</li><li>电气端子、探针、导电柱</li><li>卫浴五金、装饰配件</li></ul>'],
            ['t' => 'Brass CNC Parts', 's' => 'Machining of H59/H62/C3604 brass with excellent conductivity — ideal for fittings, valves and electrical terminals.', 'c' => '<p>Brass machines beautifully with high surface quality, and offers excellent electrical/thermal conductivity and corrosion resistance — the first choice for fluid fittings, electrical terminals, valve parts and decorative hardware.</p><h3>Service Scope</h3><ul><li>Free-machining brass H59, H62, C3604; beryllium copper on request</li><li>Mill-turn processes hold ±0.01mm on fine features</li><li>Nickel plating, chrome plating and passivation available</li></ul><h3>Applications</h3><ul><li>Pneumatic/hydraulic fittings, valve cores and seats</li><li>Electrical terminals, test probes, contact pins</li><li>Sanitary hardware and decorative fittings</li></ul>']],
        [7, 2, 'titanium-cnc-parts', 'products/titanium-cnc.jpg', 287, [1, 7],
            ['t' => '钛合金加工件', 's' => 'Gr2/Gr5 钛合金精密加工，攻克导热差、易粘刀难题，服务医疗植入与航空客户。', 'c' => '<p>钛合金比强度高、生物相容性好，但导热差、加工硬化严重，是公认的难加工材料。傲锋积累了十余年钛合金加工经验，为医疗器械与航空航天客户提供稳定交付。</p><h3>工艺方案</h3><ul><li>低温高压冷却系统，抑制刀尖积屑瘤</li><li>专用硬质合金刀具，小切深高进给策略</li><li>Gr2、Gr5（Ti-6Al-4V）、Ti-6Al-7Nb 常备材料</li><li>加工后去应力退火，尺寸长期稳定</li></ul><h3>典型产品</h3><ul><li>骨科植入物试制件、手术器械</li><li>航空紧固件、无人机结构件</li><li>高端运动器材与钟表零件</li></ul>'],
            ['t' => 'Titanium CNC Parts', 's' => 'Precision machining of Gr2/Gr5 titanium, solving poor thermal conductivity and work hardening for medical and aerospace clients.', 'c' => '<p>Titanium offers an outstanding strength-to-weight ratio and biocompatibility, yet its poor thermal conductivity and severe work hardening make it notoriously difficult to machine. With over a decade of titanium experience, Apex delivers stable quality for medical and aerospace clients.</p><h3>Process Solutions</h3><ul><li>High-pressure coolant to suppress built-up edge</li><li>Dedicated carbide tooling with low-DOC, high-feed strategies</li><li>Gr2, Gr5 (Ti-6Al-4V) and Ti-6Al-7Nb stocked</li><li>Post-machining stress relief for long-term stability</li></ul><h3>Typical Products</h3><ul><li>Orthopedic implant prototypes, surgical instruments</li><li>Aerospace fasteners, UAV structures</li><li>Premium sporting goods and watch components</li></ul>']],
        [8, 3, 'sheet-metal-enclosures', 'products/sheet-enclosure.jpg', 298, [3, 2],
            ['t' => '定制钣金机箱机柜', 's' => '激光切割、数控折弯、焊接铆接一体化，定制设备机箱、机柜与结构件，支持小批量快反。', 'c' => '<p>傲锋钣金事业部提供从激光下料、折弯成型到焊接装配的完整产线，为自动化设备、通讯、医疗与新能源客户定制机箱机柜及结构件。</p><h3>加工能力</h3><ul><li>6kW 激光切割：碳钢 ≤ 25mm，不锈钢 ≤ 12mm，铝板 ≤ 10mm</li><li>数控折弯 160T，最长 3200mm</li><li>氩弧焊、气保焊、激光焊与种钉、铆接</li><li>配套喷粉、喷塑、丝印一站式交付</li></ul><h3>服务优势</h3><ul><li>DFM 可制造性评审，优化折弯与焊接工艺</li><li>打样 5–10 天，小批量 15–20 天</li><li>整机组装与老化测试支持</li></ul>'],
            ['t' => 'Custom Sheet Metal Enclosures', 's' => 'Laser cutting, CNC bending and welding under one roof — custom equipment enclosures and frames with fast low-volume turnaround.', 'c' => '<p>Apex\'s sheet metal division runs a complete line from laser blanking and bending to welding and assembly, building enclosures and structural parts for automation, telecom, medical and new-energy customers.</p><h3>Capabilities</h3><ul><li>6kW laser: carbon steel ≤ 25mm, stainless ≤ 12mm, aluminum ≤ 10mm</li><li>CNC press brakes 160T, bed length up to 3200mm</li><li>TIG, MIG, laser welding plus stud welding and riveting</li><li>Powder coating, painting and silk-screening in-house</li></ul><h3>Service Advantages</h3><ul><li>DFM review to optimize bending and welding</li><li>Prototypes in 5–10 days, low-volume in 15–20 days</li><li>Full assembly and burn-in testing supported</li></ul>']],
        [9, 3, 'stainless-steel-sheet-metal', 'products/stainless-sheet.jpg', 189, [6, 2],
            ['t' => '不锈钢钣金件', 's' => '304/316L 不锈钢钣金加工，耐腐蚀、易清洁，适用于食品机械、医疗设备与户外设施。', 'c' => '<p>不锈钢钣金件在食品机械、医疗设备、化工与户外设施中不可替代。我们加工 304、316L、201 等牌号，兼顾结构强度与外观质量。</p><h3>工艺控制</h3><ul><li>不锈钢专用切割断面，无挂渣、氧化层薄</li><li>焊接采用背面充氩保护，焊缝均匀可抛光</li><li>表面拉丝、8K 镜面、喷砂、钝化可选</li></ul><h3>典型产品</h3><ul><li>食品机械外壳与料斗</li><li>医疗推车、器械柜</li><li>户外机柜、防雨箱体</li></ul>'],
            ['t' => 'Stainless Steel Sheet Metal', 's' => '304/316L stainless fabrication — corrosion resistant and easy to clean for food machinery, medical equipment and outdoor cabinets.', 'c' => '<p>Stainless steel fabrication is irreplaceable in food machinery, medical equipment, chemical plants and outdoor infrastructure. We process 304, 316L and 201 grades with equal attention to structural strength and appearance.</p><h3>Process Control</h3><ul><li>Clean laser-cut edges with minimal dross and oxide layer</li><li>Back-purged TIG welding produces polishable beads</li><li>Hairline, 8K mirror, bead blast and passivation finishes</li></ul><h3>Typical Products</h3><ul><li>Food machinery housings and hoppers</li><li>Medical carts and instrument cabinets</li><li>Outdoor cabinets and weatherproof enclosures</li></ul>']],
        [10, 4, 'aluminum-die-casting-parts', 'products/aluminum-die-casting.jpg', 267, [5, 3],
            ['t' => '铝合金压铸件', 's' => 'ADC12/A380 高压压铸，80–800T 机台覆盖中小件，配套 CNC 精加工与气密性测试。', 'c' => '<p>压铸适合大批量、形状复杂的铝合金结构件，单件节拍可达数十秒。傲锋配备 80–800T 冷室压铸机 12 台，年产压铸件超 500 万件。</p><h3>生产能力</h3><ul><li>ADC12、A380、A360、AlSi10MnMg 等材料</li><li>模流分析（Moldflow）前置评审，降低缩孔风险</li><li>X-Ray 探伤 + CMM 全尺寸检测</li><li>配套 CNC 二次加工、攻牙、去毛刺与喷粉</li></ul><h3>典型应用</h3><ul><li>汽车发动机支架、变速箱壳体</li><li>LED 灯具散热器、通讯滤波器腔体</li><li>电动工具外壳、电机端盖</li></ul>'],
            ['t' => 'Aluminum Die Casting Parts', 's' => 'ADC12/A380 high-pressure die casting on 80–800T machines, with CNC finishing and leak testing in-house.', 'c' => '<p>Die casting suits high-volume, geometrically complex aluminum structures with cycle times of just seconds. Apex runs twelve 80–800T cold-chamber machines, producing over 5 million castings per year.</p><h3>Production Capabilities</h3><ul><li>ADC12, A380, A360, AlSi10MnMg alloys</li><li>Upfront mold-flow analysis to minimize porosity</li><li>X-ray inspection plus CMM dimensional checks</li><li>Secondary CNC machining, tapping, deburring and powder coating</li></ul><h3>Typical Applications</h3><ul><li>Engine brackets, transmission housings</li><li>LED heat sinks, telecom filter cavities</li><li>Power-tool housings, motor end caps</li></ul>']],
        [11, 4, 'zinc-alloy-die-casting', 'products/zinc-die-casting.jpg', 154, [3],
            ['t' => '锌合金压铸件', 's' => '3# / 5# 锌合金热室压铸，精度高、表面质量好，适合锁具、汽配与装饰五金。', 'c' => '<p>锌合金熔点低、流动性好，可采用热室压铸实现高精度与优异表面质量，特别适合外观件与小型精密件。</p><h3>工艺特点</h3><ul><li>热室压铸机 25–160T，节拍快、成本低</li><li>尺寸精度可达 ±0.02mm，表面光洁度高</li><li>配套抛光、电镀（镀锌/镍/铬）、喷涂</li></ul><h3>典型产品</h3><ul><li>锁具锁体、拉手合页</li><li>汽车标牌、雨刮配件</li><li>箱包五金、卫浴挂件</li></ul>'],
            ['t' => 'Zinc Alloy Die Casting', 's' => 'Hot-chamber zinc die casting (3#/5#) with tight accuracy and premium surface quality for locks, auto trim and hardware.', 'c' => '<p>Zinc alloys\' low melting point and excellent fluidity enable hot-chamber die casting with tight accuracy and superb surface quality — ideal for cosmetic and small precision parts.</p><h3>Process Features</h3><ul><li>25–160T hot-chamber machines, fast cycles, low cost</li><li>Dimensional accuracy to ±0.02mm with fine surface finish</li><li>Polishing and plating (zinc/nickel/chrome) in-house</li></ul><h3>Typical Products</h3><ul><li>Lock bodies, handles and hinges</li><li>Automotive badges, wiper components</li><li>Luggage hardware, bathroom accessories</li></ul>']],
        [12, 5, 'anodizing-powder-coating', 'products/anodizing.jpg', 221, [5],
            ['t' => '阳极氧化与喷粉服务', 's' => '自有阳极氧化线与喷粉线，膜厚可控、色差 ΔE ≤ 1.5，满足外观件与防腐要求。', 'c' => '<p>表面处理决定产品的第一印象。傲锋自有阳极氧化与静电喷粉产线，关键外观指标全程受控。</p><h3>阳极氧化</h3><ul><li>普通氧化膜厚 10–25μm，硬质氧化可达 50μm</li><li>本色、黑色及潘通色卡定制着色</li><li>盐雾测试 ≥ 48h（按 ASTM B117）</li></ul><h3>静电喷粉</h3><ul><li>环氧、聚酯、环氧聚酯混合粉末</li><li>膜厚 60–120μm，百格测试 5B</li><li>色差 ΔE ≤ 1.5，光泽度按样板定制</li></ul>'],
            ['t' => 'Anodizing & Powder Coating', 's' => 'In-house anodizing and powder coating lines with controlled film thickness and color difference ΔE ≤ 1.5.', 'c' => '<p>Surface finishing defines the first impression of a product. Apex operates its own anodizing and electrostatic powder-coating lines with all key cosmetic metrics under control.</p><h3>Anodizing</h3><ul><li>Standard film 10–25μm, hard anodizing up to 50μm</li><li>Clear, black and custom Pantone colors</li><li>Salt spray ≥ 48h per ASTM B117</li></ul><h3>Powder Coating</h3><ul><li>Epoxy, polyester and hybrid powders</li><li>Film 60–120μm, cross-cut adhesion 5B</li><li>ΔE ≤ 1.5, gloss customized to samples</li></ul>']],
        [13, 5, 'polishing-electroplating', 'products/polishing.jpg', 143, [6],
            ['t' => '抛光、电镀与钝化', 's' => '机械抛光/电解抛光、镀镍镀铬、不锈钢钝化，提升零件外观、耐磨与防腐性能。', 'c' => '<p>针对高外观与高防腐需求，傲锋提供完整的精整工艺组合。</p><h3>抛光</h3><ul><li>机械抛光：镜面效果 Ra ≤ 0.05</li><li>电解抛光：不锈钢件表面光洁、去毛刺彻底</li></ul><h3>电镀</h3><ul><li>镀镍、镀铬、镀金、镀锡（外协认证产线）</li><li>膜厚 X-Ray 检测，符合 RoHS/REACH</li></ul><h3>钝化</h3><ul><li>不锈钢柠檬酸钝化，盐雾 ≥ 96h 无红锈</li><li>铝件化学转化膜（铬化/无铬）</li></ul>'],
            ['t' => 'Polishing, Plating & Passivation', 's' => 'Mechanical/electrolytic polishing, nickel and chrome plating, and passivation for superior looks, wear and corrosion resistance.', 'c' => '<p>For demanding cosmetic and corrosion requirements, Apex offers a complete set of finishing processes.</p><h3>Polishing</h3><ul><li>Mechanical polishing to mirror finish, Ra ≤ 0.05</li><li>Electropolishing for stainless parts — bright, fully deburred</li></ul><h3>Plating</h3><ul><li>Nickel, chrome, gold and tin plating (certified partner lines)</li><li>XRF thickness verification, RoHS/REACH compliant</li></ul><h3>Passivation</h3><ul><li>Citric-acid passivation for stainless, ≥ 96h salt spray without red rust</li><li>Chemical conversion coatings for aluminum (chromate / chrome-free)</li></ul>']],
        [14, 6, 'manufacturing-solutions-overview', 'industries/manufacturing.jpg', 352, [3, 4],
            ['t' => '一站式精密制造解决方案', 's' => '从设计评审、打样验证到量产交付与售后支持，傲锋为各行业客户提供端到端的精密制造服务。', 'c' => '<p>不同行业对零部件的要求各有侧重：汽车看重过程能力与追溯，医疗强调洁净与合规，航空聚焦材料与认证，消费电子关注外观与成本。傲锋以统一的质量体系为底座，为各行业提供定制化制造方案。</p><h3>端到端服务流程</h3><ul><li>DFM 设计评审：优化结构以降本增效</li><li>快速打样：7–15 天交付首件并附全尺寸报告</li><li>小批量验证：PPAP/FAI 文件齐套</li><li>量产交付：安全库存与滚动预测管理</li><li>售后支持：8D 报告 24 小时响应</li></ul>'],
            ['t' => 'One-Stop Precision Manufacturing Solutions', 's' => 'From design review and prototyping through mass production and after-sales support — end-to-end precision manufacturing for every industry.', 'c' => '<p>Every industry weights part requirements differently: automotive demands process capability and traceability, medical emphasizes cleanliness and compliance, aerospace focuses on materials and certification, and consumer electronics cares about cosmetics and cost. Apex builds on a unified quality system to deliver tailored manufacturing solutions.</p><h3>End-to-End Workflow</h3><ul><li>DFM review: optimize designs to cut cost and risk</li><li>Rapid prototyping: first articles in 7–15 days with full reports</li><li>Low-volume validation: complete PPAP/FAI documentation</li><li>Mass production: safety stock and rolling-forecast management</li><li>After-sales: 8D response within 24 hours</li></ul>']],
        [15, 7, 'precision-automotive-components', 'industries/automotive.jpg', 301, [4, 2],
            ['t' => '汽车精密零部件', 's' => '通过 IATF 16949 认证，为传统动力与新能源三电系统提供精密机加工与压铸零部件。', 'c' => '<p>傲锋通过 IATF 16949 汽车行业质量体系认证，量产件过程能力 CPK ≥ 1.67，全流程条码追溯。</p><h3>供应产品</h3><ul><li>发动机与变速箱壳体、支架、法兰</li><li>新能源电机壳体、电控散热基座、电池包结构件</li><li>转向与制动系统精密轴类、阀体</li><li>传感器外壳与连接器零件</li></ul><h3>过程控制</h3><ul><li>APQP 全流程项目管理，PPAP Level 3 交付</li><li>SPC 关键尺寸监控，MSA 量具分析</li><li>三坐标、轮廓仪、粗糙度仪全尺寸检测</li></ul>'],
            ['t' => 'Precision Automotive Components', 's' => 'IATF 16949 certified machining and die casting for conventional powertrains and new-energy EV systems.', 'c' => '<p>Apex is certified to IATF 16949, with production process capability of CPK ≥ 1.67 and full barcode traceability.</p><h3>Products Supplied</h3><ul><li>Engine and transmission housings, brackets, flanges</li><li>EV motor housings, inverter heat-sink bases, battery-pack structures</li><li>Precision shafts and valve bodies for steering and braking</li><li>Sensor housings and connector components</li></ul><h3>Process Control</h3><ul><li>APQP program management, PPAP Level 3 submission</li><li>SPC on critical dimensions, MSA gauge analysis</li><li>CMM, profilometer and roughness inspection</li></ul>']],
        [16, 8, 'medical-device-components', 'industries/medical.jpg', 276, [4, 2],
            ['t' => '医疗器械零部件', 's' => 'ISO 13485 体系管控，万级洁净车间，为诊断设备、手术器械与植入器械提供精密零件。', 'c' => '<p>医疗行业对零件的精度、洁净度与可追溯性要求严苛。傲锋按照 ISO 13485 建立医疗器械质量管理体系，配备万级洁净装配间。</p><h3>供应产品</h3><ul><li>诊断与影像设备结构件、外壳</li><li>手术器械零件：钳口、关节、手柄</li><li>内窥镜零件、牙科手机零件</li><li>骨科植入物试制件（钛合金）</li></ul><h3>合规保障</h3><ul><li>材料生物相容性报告（ISO 10993 支持文件）</li><li>批次全流程追溯，记录保存 ≥ 15 年</li><li>超声波清洗 + 洁净包装</li></ul>'],
            ['t' => 'Medical Device Components', 's' => 'ISO 13485 controlled manufacturing with cleanroom assembly for diagnostics, surgical instruments and implant prototypes.', 'c' => '<p>The medical industry imposes strict demands on precision, cleanliness and traceability. Apex operates an ISO 13485 quality system with Class 10,000 clean assembly rooms.</p><h3>Products Supplied</h3><ul><li>Structural parts and housings for diagnostic and imaging equipment</li><li>Surgical instrument parts: jaws, joints, handles</li><li>Endoscope and dental handpiece components</li><li>Titanium orthopedic implant prototypes</li></ul><h3>Compliance</h3><ul><li>Biocompatibility documentation support (ISO 10993)</li><li>Full batch traceability, records retained ≥ 15 years</li><li>Ultrasonic cleaning and clean packaging</li></ul>']],
        [17, 9, 'aerospace-machined-parts', 'industries/aerospace.jpg', 234, [7, 2],
            ['t' => '航空航天加工件', 's' => '钛合金、高温合金与高强度铝合金加工能力，满足航空航天对材料与精度的严苛要求。', 'c' => '<p>航空航天零件要求高强度重量比、耐高温与极端可靠性。傲锋为无人机、卫星部件与航空地面设备客户提供难加工材料解决方案。</p><h3>材料能力</h3><ul><li>钛合金 Gr2/Gr5/Gr23</li><li>高温合金 Inconel 718、Hastelloy</li><li>高强铝 7075、2024、7050</li></ul><h3>质量保障</h3><ul><li>五轴加工 + 在线测量，位置度 ≤ 0.02mm</li><li>原材料光谱分析（PMI）逐批验证</li><li>荧光渗透探伤（FPI）支持</li></ul>'],
            ['t' => 'Aerospace Machined Parts', 's' => 'Titanium, superalloy and high-strength aluminum machining that meets aerospace demands for materials and precision.', 'c' => '<p>Aerospace parts demand high strength-to-weight ratios, temperature resistance and extreme reliability. Apex provides difficult-material solutions for UAV, satellite and aviation ground-equipment customers.</p><h3>Material Capabilities</h3><ul><li>Titanium Gr2 / Gr5 / Gr23</li><li>Superalloys: Inconel 718, Hastelloy</li><li>High-strength aluminum: 7075, 2024, 7050</li></ul><h3>Quality Assurance</h3><ul><li>5-axis machining with on-machine probing, true position ≤ 0.02mm</li><li>Per-batch PMI spectrographic verification</li><li>Fluorescent penetrant inspection (FPI) support</li></ul>']],
        [18, 10, 'electronic-housings-components', 'industries/electronics.jpg', 258, [5, 2],
            ['t' => '消费电子精密结构件', 's' => '兼顾外观与精度的消费电子金属件：外壳、散热件、屏蔽罩与连接器零件。', 'c' => '<p>消费电子产品对金属结构件的外观与精度同时敏感。傲锋为耳机、相机、智能穿戴与通讯设备品牌提供外观级精密零件。</p><h3>供应产品</h3><ul><li>铝合金一体外壳（CNC + 阳极氧化）</li><li>散热器、屏蔽罩、弹片</li><li>Type-C 连接器零件、SIM 卡托</li><li>智能穿戴中框与表壳</li></ul><h3>外观管控</h3><ul><li>A 级面管控标准，限度样板封样管理</li><li>色差 ΔE ≤ 1.0，膜厚在线监控</li><li>全检 + AOI 外观筛选</li></ul>'],
            ['t' => 'Consumer Electronics Components', 's' => 'Cosmetic-grade precision metal parts for electronics: housings, heat sinks, shields and connector components.', 'c' => '<p>Consumer electronics are simultaneously sensitive to cosmetics and precision. Apex supplies cosmetic-grade metal parts to earphone, camera, wearable and telecom device brands.</p><h3>Products Supplied</h3><ul><li>Unibody aluminum housings (CNC + anodizing)</li><li>Heat sinks, shielding cans, contact springs</li><li>Type-C connector parts, SIM trays</li><li>Wearable frames and watch cases</li></ul><h3>Cosmetic Control</h3><ul><li>Class-A surface standards with limit-sample management</li><li>ΔE ≤ 1.0 color control, in-line film-thickness monitoring</li><li>100% inspection plus AOI cosmetic screening</li></ul>']],
        [19, 11, 'apex-expands-manufacturing-capacity', 'news/new-facility.jpg', 412, [],
            ['t' => '傲锋精密二期工厂投产，产能提升 60%', 's' => '占地 6,000㎡ 的二期智造工厂正式投产，新增 20 台 CNC 加工中心与自动化产线，整体产能提升 60%。', 'c' => '<p>2026 年 3 月，傲锋精密二期智造工厂在东莞长安正式投产。新工厂占地 6,000㎡，引入 20 台高性能 CNC 加工中心、2 条柔性加工单元（FMS）及自动化上下料系统。</p><h3>关键升级</h3><ul><li>整体机加工产能提升 60%</li><li>夜间无人值守加工，设备利用率提升至 85%</li><li>新增恒温检测室，三坐标数量翻倍</li></ul><p>总经理表示：“二期工厂的投产将显著缩短客户的交付周期，也为承接医疗与航空领域的新项目奠定了硬件基础。”</p>'],
            ['t' => 'Apex Precision Opens Phase-II Plant, Boosting Capacity by 60%', 's' => 'Our new 6,000㎡ smart factory is now operational with 20 additional CNC centers and automation lines — total capacity up 60%.', 'c' => '<p>In March 2026, Apex Precision officially commissioned its Phase-II smart factory in Chang\'an, Dongguan. The 6,000㎡ facility adds 20 high-performance CNC centers, two flexible manufacturing systems (FMS) and automated loading.</p><h3>Key Upgrades</h3><ul><li>Overall machining capacity increased by 60%</li><li>Lights-out night machining raises utilization to 85%</li><li>New temperature-controlled metrology room doubles CMM capacity</li></ul><p>“The Phase-II plant shortens delivery cycles and lays the hardware foundation for new medical and aerospace programs,” said the General Manager.</p>']],
        [20, 11, 'precision-machining-trends-2026', 'news/industry-trend.jpg', 388, [],
            ['t' => '2026 精密加工行业三大趋势', 's' => '五轴普及化、AI 辅助编程与近岸供应链重构，正在重塑精密加工行业的竞争格局。', 'c' => '<p>2026 年，精密加工行业正经历深刻变革。我们观察到三大趋势：</p><h3>一、五轴加工加速普及</h3><p>五轴设备价格持续下探，越来越多工厂将其作为标准配置。工序集中带来的交期优势，正在成为订单竞争的关键变量。</p><h3>二、AI 进入 CAM 编程</h3><p>AI 辅助刀路生成与加工参数优化开始规模化落地，编程效率提升 3–5 倍，新手工程师也能输出稳定工艺。</p><h3>三、供应链近岸化</h3><p>欧美客户在保留中国供应链的同时布局近岸备份，“中国 + 1”策略使具备快速响应与工程服务能力的工厂更受青睐。</p>'],
            ['t' => 'Three Trends Reshaping Precision Machining in 2026', 's' => '5-axis adoption, AI-assisted CAM and nearshore supply chains are redrawing the competitive landscape of precision machining.', 'c' => '<p>The precision machining industry is undergoing profound change in 2026. We see three defining trends:</p><h3>1. 5-Axis Goes Mainstream</h3><p>Falling equipment prices make five-axis a standard configuration for more shops. The lead-time advantage of consolidated operations is becoming decisive in winning orders.</p><h3>2. AI Enters CAM</h3><p>AI-assisted toolpath generation and cutting-parameter optimization are scaling, boosting programming efficiency 3–5x and enabling junior engineers to deliver stable processes.</p><h3>3. Nearshoring Reshapes Supply Chains</h3><p>Western buyers keep China supply lines while building nearshore backups. The “China + 1” strategy favors factories with fast response and strong engineering services.</p>']],
        [21, 12, 'iso-certification-renewal-2026', 'news/iso-certification.jpg', 356, [4],
            ['t' => '傲锋精密顺利通过 ISO 9001:2015 年度监督审核', 's' => '审核组对过程控制与追溯体系给予高度评价，质量管理体系连续 8 年零不符合项通过。', 'c' => '<p>2026 年 5 月，第三方认证机构对傲锋精密进行了 ISO 9001:2015 年度监督审核。审核覆盖设计开发、采购、生产、检测与交付全流程，公司以零不符合项的成绩连续第 8 年通过审核。</p><p>审核组特别肯定了公司在关键尺寸 SPC 监控与批次追溯方面的实践，认为体系运行“有效且具有行业示范意义”。</p><p>目前，傲锋已建立 ISO 9001、IATF 16949、ISO 13485 三大体系融合的质量管理平台，为客户提供统一的高标准质量保障。</p>'],
            ['t' => 'Apex Passes ISO 9001:2015 Surveillance Audit — 8th Consecutive Year', 's' => 'Auditors praised our process control and traceability; the QMS passed with zero nonconformities for the eighth straight year.', 'c' => '<p>In May 2026, a third-party certification body conducted the annual ISO 9001:2015 surveillance audit at Apex Precision. Covering design, purchasing, production, inspection and delivery, the company passed with zero nonconformities — the eighth consecutive year.</p><p>Auditors highlighted our SPC monitoring of critical dimensions and batch traceability, describing the system as “effective and exemplary for the industry.”</p><p>Apex now runs an integrated quality platform spanning ISO 9001, IATF 16949 and ISO 13485, delivering a unified high standard of quality assurance.</p>']],
        [22, 12, 'five-axis-machining-centers-commissioned', 'news/automation.jpg', 298, [7],
            ['t' => '4 台五轴加工中心完成安装调试', 's' => '新引进的四台五轴联动加工中心完成验收，五轴设备总数达 12 台，复杂零件产能翻倍。', 'c' => '<p>6 月，傲锋新引进的 4 台五轴联动加工中心全部完成安装调试并通过验收，公司五轴设备总数达到 12 台。</p><h3>新增设备亮点</h3><ul><li>定位精度 0.003mm，配备在线测头与刀具破损检测</li><li>支持钛合金、高温合金重切削</li><li>接入 MES 系统，加工数据实时采集</li></ul><p>设备负责人介绍，新产线将使复杂零件的平均交期从 15 天缩短至 10 天，并进一步支撑航空与医疗项目的产能需求。</p>'],
            ['t' => 'Four New 5-Axis Machining Centers Commissioned', 's' => 'Our five-axis fleet reaches 12 machines after four new centers passed acceptance — complex-part capacity doubled.', 'c' => '<p>In June, Apex commissioned four new simultaneous 5-axis machining centers, bringing the total five-axis fleet to 12 machines.</p><h3>New Equipment Highlights</h3><ul><li>0.003mm positioning accuracy with on-machine probing and tool-breakage detection</li><li>Heavy cutting capability for titanium and superalloys</li><li>MES-connected for real-time production data</li></ul><p>The new line shortens average lead times for complex parts from 15 to 10 days and further supports aerospace and medical program capacity, according to our equipment manager.</p>']],
        [23, 12, 'apex-at-canton-fair-2026', 'news/trade-show.jpg', 267, [],
            ['t' => '傲锋精密亮相 2026 春季广交会', 's' => '五天展期接待来自 32 个国家的 400 余位采购商，现场达成多项打样合作意向。', 'c' => '<p>4 月，傲锋精密携 CNC 加工、钣金与压铸三大产品系列亮相第 139 届广交会加工机械与零部件展区。</p><p>五天展期内，公司展台共接待来自 32 个国家的 400 余位专业采购商，现场收集图纸询价 120 余份，并与多家欧洲自动化设备制造商达成打样合作意向。</p><p>海外事业部负责人表示：“广交会是展示中国精密制造能力的最佳窗口。我们将持续参加国内外专业展会，与全球客户面对面交流。”</p>'],
            ['t' => 'Apex Precision at the 2026 Spring Canton Fair', 's' => 'Over 400 buyers from 32 countries visited our booth; multiple prototyping partnerships were initiated on site.', 'c' => '<p>In April, Apex Precision showcased its CNC machining, sheet metal and die casting portfolios at the 139th Canton Fair.</p><p>During the five-day event, our booth hosted over 400 professional buyers from 32 countries, collected more than 120 drawing inquiries, and initiated prototyping partnerships with several European automation equipment manufacturers.</p><p>“The Canton Fair is the best window to showcase China\'s precision manufacturing capability. We will keep attending professional exhibitions worldwide,” said the head of our overseas division.</p>']],
        [24, 12, 'rd-center-officially-launched', 'news/rd-center.jpg', 198, [],
            ['t' => '工程技术研发中心正式揭牌', 's' => '研发中心聚焦 DFM 工程服务、新材料工艺与自动化产线研发，工程师团队扩编至 35 人。', 'c' => '<p>2 月，傲锋精密工程技术研发中心正式揭牌。中心下设工艺工程、自动化与检测技术三个部门，工程师团队扩编至 35 人。</p><h3>重点方向</h3><ul><li>客户图纸 DFM 优化与成本工程</li><li>钛合金、复合材料等新材料加工工艺开发</li><li>柔性加工单元与在线检测自动化</li></ul><p>研发中心的成立标志着傲锋从“来图加工”向“工程服务型制造”的战略升级。</p>'],
            ['t' => 'Engineering R&D Center Officially Launched', 's' => 'The new center focuses on DFM services, new-material processes and automation; the engineering team grows to 35.', 'c' => '<p>In February, Apex Precision officially launched its Engineering R&D Center, organized into process engineering, automation and metrology divisions, with the engineering team expanded to 35 members.</p><h3>Key Focus Areas</h3><ul><li>DFM optimization and cost engineering for customer drawings</li><li>Process development for titanium, composites and new materials</li><li>Flexible manufacturing cells and in-line inspection automation</li></ul><p>The center marks Apex\'s strategic upgrade from build-to-print machining to engineering-service manufacturing.</p>']],
        [25, 13, 'cnc-automation-transforming-manufacturing', 'news/cnc-technology.jpg', 245, [],
            ['t' => '自动化产线如何改变 CNC 加工成本结构', 's' => '机器人上下料与柔性制造系统让夜间无人加工成为常态，单件人工成本下降 40% 以上。', 'c' => '<p>随着机器人上下料与柔性制造系统（FMS）的成熟，CNC 加工的夜班无人值守已从概念走向常态。</p><h3>成本结构的变化</h3><ul><li>设备利用率从 55% 提升至 85% 以上</li><li>单件分摊人工成本下降 40%–60%</li><li>质量波动收窄：夜间加工一致性反而更高</li></ul><p>业内专家认为，未来三年，自动化能力将成为中小加工厂能否进入头部客户供应链的分水岭。具备自动化产线与在线检测能力的工厂，将在报价竞争中占据结构性优势。</p>'],
            ['t' => 'How Automation Is Changing CNC Machining Economics', 's' => 'Robotic loading and FMS make lights-out machining routine, cutting per-part labor cost by over 40%.', 'c' => '<p>As robotic loading and flexible manufacturing systems (FMS) mature, lights-out CNC machining has moved from concept to routine.</p><h3>Shifting Cost Structures</h3><ul><li>Equipment utilization rises from 55% to over 85%</li><li>Per-part labor cost falls 40%–60%</li><li>Variation narrows — overnight consistency often improves</li></ul><p>Industry experts expect automation capability to become the dividing line for entering top-tier supply chains within three years. Shops with automated lines and in-line inspection will hold a structural advantage in quoting.</p>']],
        [26, 13, 'local-sourcing-reshapes-supply-chain', 'news/supply-chain.jpg', 187, [],
            ['t' => '近岸采购兴起，中国精密制造如何应对', 's' => '“中国 + 1”策略下，响应速度、工程服务与质量体系成为留住海外订单的核心竞争力。', 'c' => '<p>近年来，欧美采购方在保留中国供应链的同时加速近岸布局，“中国 + 1”成为主流采购策略。这给中国精密制造企业带来了新的课题。</p><h3>留住订单的三个关键</h3><ul><li><strong>速度</strong>：24 小时报价、7 天打样成为入场门槛</li><li><strong>工程服务</strong>：DFM 优化能力帮助客户降本，形成粘性</li><li><strong>体系信任</strong>：IATF/AS/ISO 认证与可追溯数据是基础</li></ul><p>分析师指出，单纯依靠价格优势的时代已经过去。能够提供“制造 + 工程服务”综合价值的工厂，仍将在全球供应链中保持不可替代的位置。</p>'],
            ['t' => 'Nearshoring Rises: How Chinese Precision Manufacturing Responds', 's' => 'Under “China + 1”, response speed, engineering services and quality systems are the keys to retaining overseas orders.', 'c' => '<p>Western buyers are accelerating nearshore layouts while keeping Chinese supply lines — “China + 1” has become the mainstream sourcing strategy, posing new questions for Chinese precision manufacturers.</p><h3>Three Keys to Retaining Orders</h3><ul><li><strong>Speed</strong>: 24-hour quoting and 7-day prototyping are table stakes</li><li><strong>Engineering</strong>: DFM optimization cuts customer costs and builds loyalty</li><li><strong>Trust</strong>: IATF/AS/ISO certifications and traceable data are foundational</li></ul><p>Analysts note the era of competing on price alone is over. Shops delivering combined “manufacturing + engineering service” value will remain indispensable in global supply chains.</p>']],
        [27, 13, 'china-precision-parts-export-growth', 'news/export-growth.jpg', 212, [],
            ['t' => '海关数据：精密零部件出口连续三个季度增长', 's' => '高端装备与新能源需求拉动下，CNC 加工件与压铸件出口额同比增长 12.6%。', 'c' => '<p>最新海关统计显示，我国精密机械零部件出口额连续三个季度保持增长，最近一季度同比增长 12.6%，其中 CNC 加工件与铝压铸件贡献最大增量。</p><h3>增长驱动因素</h3><ul><li>全球高端装备制造业复苏，设备零部件外包需求增加</li><li>新能源汽车产业链出海，带动三电系统零件出口</li><li>国内工厂自动化与质量体系升级，国际客户信任度提升</li></ul><p>行业商会提醒，出口企业应重视合规与知识产权保护，在报价阶段明确图纸与技术资料的保密条款，防范贸易风险。</p>'],
            ['t' => 'Customs Data: Precision Parts Exports Grow for Third Straight Quarter', 's' => 'Driven by high-end equipment and new energy demand, CNC and die-casting exports rose 12.6% year over year.', 'c' => '<p>The latest customs statistics show China\'s precision mechanical parts exports grew for the third consecutive quarter, up 12.6% year over year, with CNC machined parts and aluminum die castings contributing the largest increments.</p><h3>Growth Drivers</h3><ul><li>Global recovery in high-end equipment manufacturing increases outsourcing demand</li><li>EV supply chains going overseas drive motor, inverter and battery part exports</li><li>Automation and quality-system upgrades raise international buyer confidence</li></ul><p>The industry chamber reminds exporters to prioritize compliance and IP protection, clarifying NDA terms on drawings and technical documents at the quoting stage.</p>']],
    ];
}

function precision_seed_articles(callable $img): void
{
    foreach (precision_article_defs() as [$id, $catalogId, $slug, $image, $viewed, $tagIds, $zh, $en]) {
        $article = Article::query()->create(['id' => $id, 'catalog_id' => $catalogId, 'slug' => $slug, 'position' => $id, 'viewed' => $viewed, 'author' => 'Apex Precision', 'active' => 1]);
        $article->translations()->createMany([
            ['locale' => 'zh-cn', 'title' => $zh['t'], 'summary' => $zh['s'], 'image' => $img($image), 'content' => $zh['c'], 'meta_title' => $zh['t'].'｜傲锋精密', 'meta_description' => $zh['s'], 'meta_keywords' => '傲锋精密,精密加工,CNC,Apex Precision'],
            ['locale' => 'en', 'title' => $en['t'], 'summary' => $en['s'], 'image' => $img($image), 'content' => $en['c'], 'meta_title' => $en['t'].' | Apex Precision', 'meta_description' => $en['s'], 'meta_keywords' => 'Apex Precision, precision machining, CNC, OEM'],
        ]);
        if ($tagIds) {
            $article->tags()->attach($tagIds);
        }
    }
}

function precision_seed_pages(callable $img): void
{
    $pages = [
        [1, 'about', 1, 689,
            ['t' => '关于我们', 'c' => '<p><strong>傲锋精密制造有限公司（Apex Precision Manufacturing Co., Ltd.）</strong>成立于 2008 年，坐落于制造业名城东莞，是一家专注于精密零部件研发与制造的国家级高新技术企业。</p><p>公司现拥有 12,000㎡ 现代化厂房、员工 180 余人，其中工程技术人员 35 人。产品远销北美、欧洲、日韩与东南亚等 30 多个国家和地区，出口占比超过 60%。</p><p><img src="'.$img('company/factory.jpg').'" class="img-fluid rounded my-3" alt="傲锋精密生产车间"></p><h3>发展历程</h3><ul><li><strong>2008</strong> 公司成立，以 CNC 加工起步</li><li><strong>2012</strong> 通过 ISO 9001 质量体系认证</li><li><strong>2016</strong> 扩建钣金与压铸产线，转型一站式精密制造</li><li><strong>2019</strong> 通过 IATF 16949 汽车行业认证</li><li><strong>2022</strong> 获评国家级高新技术企业</li><li><strong>2026</strong> 二期智造工厂投产，产能提升 60%</li></ul><h3>企业愿景</h3><p>成为全球客户值得信赖的精密制造合作伙伴，以工程服务创造价值，以数字智造引领未来。</p><p><img src="'.$img('company/team.jpg').'" class="img-fluid rounded my-3" alt="傲锋精密工程团队"></p>'],
            ['t' => 'About Us', 'c' => '<p><strong>Apex Precision Manufacturing Co., Ltd.</strong>, founded in 2008 and headquartered in Dongguan — a world-renowned manufacturing hub — is a national high-tech enterprise dedicated to the R&amp;D and production of precision components.</p><p>Today the company operates a 12,000㎡ modern facility with 180+ employees, including 35 engineers. Our products are exported to more than 30 countries and regions across North America, Europe, Japan, Korea and Southeast Asia, with exports accounting for over 60% of revenue.</p><p><img src="'.$img('company/factory.jpg').'" class="img-fluid rounded my-3" alt="Apex Precision workshop"></p><h3>Milestones</h3><ul><li><strong>2008</strong> Founded as a CNC machining shop</li><li><strong>2012</strong> ISO 9001 certified</li><li><strong>2016</strong> Sheet metal and die casting lines added — one-stop precision manufacturing</li><li><strong>2019</strong> IATF 16949 automotive certification</li><li><strong>2022</strong> Recognized as a national high-tech enterprise</li><li><strong>2026</strong> Phase-II smart factory launched, capacity +60%</li></ul><h3>Our Vision</h3><p>To be the most trusted precision manufacturing partner for global customers — creating value through engineering services and leading the future with digital manufacturing.</p><p><img src="'.$img('company/team.jpg').'" class="img-fluid rounded my-3" alt="Apex Precision engineering team"></p>']],
        [2, 'capabilities', 2, 534,
            ['t' => '制造能力', 'c' => '<p>傲锋精密整合 CNC 加工、钣金、压铸与表面处理四大工艺，为客户提供从单件打样到十万级量产的一站式制造能力。</p><h3>主要设备</h3><table class="table table-bordered"><thead><tr><th>设备</th><th>数量</th><th>关键参数</th></tr></thead><tbody><tr><td>3轴/4轴 CNC 加工中心</td><td>43 台</td><td>行程 1500×800×600mm，精度 ±0.005mm</td></tr><tr><td>五轴联动加工中心</td><td>12 台</td><td>重复定位精度 0.003mm</td></tr><tr><td>CNC 数控车床/车铣复合</td><td>30 台</td><td>加工直径 0.5–500mm</td></tr><tr><td>激光切割机</td><td>3 台</td><td>6kW，碳钢 ≤ 25mm</td></tr><tr><td>数控折弯机</td><td>6 台</td><td>160T / 3200mm</td></tr><tr><td>冷室压铸机</td><td>12 台</td><td>80–800T</td></tr><tr><td>三坐标测量仪（CMM）</td><td>5 台</td><td>精度 0.0015mm</td></tr></tbody></table><h3>加工材料</h3><ul><li><strong>铝合金</strong>：6061、6063、7075、5083、ADC12、A380</li><li><strong>不锈钢</strong>：303、304、316L、17-4PH、2205</li><li><strong>铜合金</strong>：H59、H62、C3604、铍铜</li><li><strong>钛合金</strong>：Gr2、Gr5、Gr23</li><li><strong>工程塑料</strong>：POM、PEEK、PA、PC、PTFE</li></ul><h3>产能与交期</h3><ul><li>月产能：CNC 加工件 80 万件 / 压铸件 400 万件</li><li>打样交期：7–15 天</li><li>量产交期：25–35 天（视订单规模）</li></ul>'],
            ['t' => 'Capabilities', 'c' => '<p>Apex Precision integrates four core processes — CNC machining, sheet metal, die casting and surface finishing — to deliver one-stop manufacturing from single prototypes to 100k-volume production.</p><h3>Key Equipment</h3><table class="table table-bordered"><thead><tr><th>Equipment</th><th>Qty</th><th>Key Parameters</th></tr></thead><tbody><tr><td>3/4-axis CNC machining centers</td><td>43</td><td>Envelope 1500×800×600mm, accuracy ±0.005mm</td></tr><tr><td>Simultaneous 5-axis centers</td><td>12</td><td>Repeatability 0.003mm</td></tr><tr><td>CNC lathes / mill-turn</td><td>30</td><td>Diameter 0.5–500mm</td></tr><tr><td>Laser cutting machines</td><td>3</td><td>6kW, carbon steel ≤ 25mm</td></tr><tr><td>CNC press brakes</td><td>6</td><td>160T / 3200mm</td></tr><tr><td>Cold-chamber die casting machines</td><td>12</td><td>80–800T</td></tr><tr><td>CMM measuring machines</td><td>5</td><td>Accuracy 0.0015mm</td></tr></tbody></table><h3>Materials</h3><ul><li><strong>Aluminum</strong>: 6061, 6063, 7075, 5083, ADC12, A380</li><li><strong>Stainless steel</strong>: 303, 304, 316L, 17-4PH, 2205</li><li><strong>Brass &amp; copper</strong>: H59, H62, C3604, beryllium copper</li><li><strong>Titanium</strong>: Gr2, Gr5, Gr23</li><li><strong>Engineering plastics</strong>: POM, PEEK, PA, PC, PTFE</li></ul><h3>Capacity &amp; Lead Time</h3><ul><li>Monthly capacity: 800k CNC parts / 4M die castings</li><li>Prototypes: 7–15 days</li><li>Production: 25–35 days (volume dependent)</li></ul>']],
        [3, 'quality', 3, 421,
            ['t' => '质量保证', 'c' => '<p>质量是精密制造的生命线。傲锋建立了 ISO 9001、IATF 16949、ISO 13485 三体系融合的质量管理平台，覆盖来料、过程与出货全环节。</p><h3>体系认证</h3><ul><li>ISO 9001:2015 质量管理体系（连续 8 年零不符合项通过审核）</li><li>IATF 16949 汽车行业质量管理体系</li><li>ISO 13485 医疗器械质量管理体系</li><li>RoHS / REACH 合规</li></ul><h3>质量控制流程</h3><ul><li><strong>IQC 来料检验</strong>：光谱仪材质分析（PMI）+ 硬度抽检</li><li><strong>IPQC 过程检验</strong>：首件全尺寸报告，关键尺寸 SPC 监控</li><li><strong>OQC 出货检验</strong>：AQL 抽样 + 外观全检</li><li><strong>追溯管理</strong>：批次条码全程追溯，质量记录保存 15 年</li></ul><h3>检测设备</h3><table class="table table-bordered"><tbody><tr><th>三坐标测量仪</th><td>5 台，精度 0.0015mm</td></tr><tr><th>影像测量仪</th><td>3 台</td></tr><tr><th>粗糙度/轮廓仪</th><td>4 台</td></tr><tr><th>硬度计 / 盐雾试验箱</th><td>各 2 台</td></tr><tr><th>X-Ray 探伤仪</th><td>1 台（压铸件内部缺陷检测）</td></tr></tbody></table>'],
            ['t' => 'Quality Assurance', 'c' => '<p>Quality is the lifeline of precision manufacturing. Apex operates an integrated quality platform spanning ISO 9001, IATF 16949 and ISO 13485, covering incoming, in-process and outgoing inspection.</p><h3>Certifications</h3><ul><li>ISO 9001:2015 (passed with zero nonconformities for 8 consecutive years)</li><li>IATF 16949 automotive quality management</li><li>ISO 13485 medical device quality management</li><li>RoHS / REACH compliant</li></ul><h3>Quality Control Workflow</h3><ul><li><strong>IQC</strong>: spectrographic material analysis (PMI) + hardness sampling</li><li><strong>IPQC</strong>: first-article full dimensional reports, SPC on critical dimensions</li><li><strong>OQC</strong>: AQL sampling + 100% cosmetic inspection</li><li><strong>Traceability</strong>: batch barcode tracking, records retained for 15 years</li></ul><h3>Inspection Equipment</h3><table class="table table-bordered"><tbody><tr><th>CMM</th><td>5 units, accuracy 0.0015mm</td></tr><tr><th>Vision measuring machines</th><td>3 units</td></tr><tr><th>Roughness / profilometers</th><td>4 units</td></tr><tr><th>Hardness testers / salt-spray chambers</th><td>2 each</td></tr><tr><th>X-ray inspection</th><td>1 unit (internal defect detection for castings)</td></tr></tbody></table>']],
        [4, 'oem-odm', 4, 376,
            ['t' => 'OEM/ODM 服务', 'c' => '<p>无论是来图加工（OEM）还是联合设计开发（ODM），傲锋都以工程服务为先导，帮助客户把设计意图转化为可稳定量产的零件。</p><h3>合作流程</h3><ul><li><strong>① 需求沟通</strong>：提供 2D/3D 图纸（STEP、IGS、PDF）与技术要求</li><li><strong>② DFM 评审</strong>：48 小时内反馈可制造性分析与成本优化建议</li><li><strong>③ 报价确认</strong>：透明报价单，含材料、工艺与检测明细</li><li><strong>④ 打样验证</strong>：7–15 天交付首件，附全尺寸检测报告</li><li><strong>⑤ 小批试产</strong>：验证工艺稳定性，输出 PPAP/FAI 文件</li><li><strong>⑥ 量产交付</strong>：安全库存管理，支持 VMI 与滚动预测</li></ul><h3>常见问题</h3><table class="table table-bordered"><tbody><tr><th>最小起订量</th><td>1 件起订（打样）</td></tr><tr><th>报价周期</th><td>24 小时内</td></tr><tr><th>保密协议</th><td>可签署 NDA，图纸专人管理</td></tr><tr><th>付款方式</th><td>T/T，打样全款，量产 30% 定金</td></tr><tr><th>出口服务</th><td>FOB 深圳 / 空运 / 国际快递</td></tr></tbody></table><p>把图纸发到 <a href="mailto:sales@apexprecision.cn">sales@apexprecision.cn</a>，让我们从 DFM 评审开始。</p>'],
            ['t' => 'OEM/ODM Service', 'c' => '<p>Whether build-to-print (OEM) or joint design development (ODM), Apex leads with engineering services that turn design intent into parts ready for stable mass production.</p><h3>Workflow</h3><ul><li><strong>① Requirement</strong>: share 2D/3D drawings (STEP, IGS, PDF) and specifications</li><li><strong>② DFM review</strong>: manufacturability analysis and cost optimization within 48 hours</li><li><strong>③ Quotation</strong>: transparent quote covering material, process and inspection</li><li><strong>④ Prototyping</strong>: first articles in 7–15 days with full dimensional reports</li><li><strong>⑤ Pilot run</strong>: process validation with complete PPAP/FAI documentation</li><li><strong>⑥ Mass production</strong>: safety stock management, VMI and rolling forecasts supported</li></ul><h3>FAQ</h3><table class="table table-bordered"><tbody><tr><th>Minimum order</th><td>1 piece (prototyping)</td></tr><tr><th>Quotation time</th><td>Within 24 hours</td></tr><tr><th>Confidentiality</th><td>NDA available, drawings access-controlled</td></tr><tr><th>Payment terms</th><td>T/T; 100% for samples, 30% deposit for production</td></tr><tr><th>Shipping</th><td>FOB Shenzhen / air freight / international express</td></tr></tbody></table><p>Send your drawings to <a href="mailto:sales@apexprecision.cn">sales@apexprecision.cn</a> — let\'s start with a DFM review.</p>']],
        [5, 'contact', 5, 655,
            ['t' => '联系我们', 'c' => '<p>欢迎垂询报价、预约验厂或洽谈合作。我们的工程销售团队将在 24 小时内回复。</p><h3>联系方式</h3><table class="table table-bordered"><tbody><tr><th>销售热线</th><td>+86-769-8123-4567</td></tr><tr><th>邮箱</th><td><a href="mailto:sales@apexprecision.cn">sales@apexprecision.cn</a></td></tr><tr><th>地址</th><td>广东省东莞市长安镇高盛路 8 号 傲锋精密产业园</td></tr><tr><th>工作时间</th><td>周一至周六 8:30 – 18:00（GMT+8）</td></tr></tbody></table><h3>验厂与参观</h3><p>我们欢迎全球客户预约现场验厂。工厂距深圳宝安国际机场 40 分钟车程，可提供接机服务。</p><p><strong>提示：</strong>本页为 InnoCMS 演示数据，联系方式均为示例。</p>'],
            ['t' => 'Contact Us', 'c' => '<p>Contact us for quotations, factory audits or partnership discussions. Our engineering sales team replies within 24 hours.</p><h3>Contact Information</h3><table class="table table-bordered"><tbody><tr><th>Sales hotline</th><td>+86-769-8123-4567</td></tr><tr><th>Email</th><td><a href="mailto:sales@apexprecision.cn">sales@apexprecision.cn</a></td></tr><tr><th>Address</th><td>No. 8 Gaosheng Road, Chang\'an Town, Dongguan, Guangdong, China</td></tr><tr><th>Business hours</th><td>Mon–Sat 8:30 – 18:00 (GMT+8)</td></tr></tbody></table><h3>Factory Visits</h3><p>We welcome on-site audits from global customers by appointment. The factory is a 40-minute drive from Shenzhen Bao\'an International Airport; pickup service is available.</p><p><strong>Note:</strong> this page is InnoCMS demo data — all contact details are examples.</p>']],
    ];
    foreach ($pages as [$id, $slug, $pos, $viewed, $zh, $en]) {
        Page::query()->create(['id' => $id, 'slug' => $slug, 'position' => $pos, 'viewed' => $viewed, 'active' => 1]);
        Page\Translation::query()->create(['page_id' => $id, 'locale' => 'zh-cn', 'title' => $zh['t'], 'content' => $zh['c'], 'meta_title' => $zh['t'].'｜傲锋精密', 'meta_description' => $zh['t'], 'meta_keywords' => '傲锋精密,Apex Precision']);
        Page\Translation::query()->create(['page_id' => $id, 'locale' => 'en', 'title' => $en['t'], 'content' => $en['c'], 'meta_title' => $en['t'].' | Apex Precision', 'meta_description' => $en['t'], 'meta_keywords' => 'Apex Precision']);
    }
}
